---
- hosts: pub
  become: true
  become_user: root
  tasks:
    - name: Apache and FTP are running 
      service:
        name: "{{ item }}"
        state: started
      loop:
         - httpd
         - vsftpd
...
