---
- hosts: dev
  become: true
  become_user: root
  tasks:
        - name: Installation of httpd and Firewalld
          yum:
                name: 
                 - httpd
                 - firewalld
        - name: Creation of index.html
          copy:
                content: "Welcome to New Automation Service"
                dest: "/var/www/html/index.html"
        - name: Start and Enable firewalld
          service:
                name: firewalld
                state: started
                enabled: true
        - name: "Firewall permits access to httpd service"
          firewalld:
                service: http
                permanent: true
                state: enabled
                immediate: yes
        - name: "Start and Enabled httpd"
          service:
                name: httpd
                state: started
                enabled: true
- name: Test Intranet web server connectivity
  hosts: localhost
  become: no
  tasks:
        - name: Connect to Intranet web server
          uri:
                url: http://server.exxample.com
                return_content: yes
                status_code: 200
...
