---
- hosts: pub
  become: true
  become_user: root
  tasks:
    - name: Mount the OS Media Drive
      command:  Mount /dev/sro /mnt
    - name: Copy the local repo file
      copy:
         src: /home/aukhan/ansible/server.repo
         dest: /etc/yum.repos.d
    - name: Installing multiple packages
      yum:
        name: "{{ item }}"
        state: latest
        with_item:
           - httpd
           - vsftpd
           - postfix
           - dovecot
    - name: start and enabled VSFTPD service
      service: 
         name: vsftpd
         state: started
         enabled: true
    - name: start and enabled VSFTPD service
      service:
         name: httpd
         state: started
         enabled: true
    - name: Create web content
      copy:
         src: /home/aukhan/roles/myhost/files/html
         dest: /var/www/vhosts/{{ansible_hostname}}
      notify:
        - restart_httpd

# Handlers for restarting httpd
  handlers:
     - name: restart_httpd
       service:
          name: httpd
          state: restarted
