---
- hosts: pub
  become: true
  become_user: root
  vars_files:
     - secret.yml
  tasks:
     - name: User Creation
       user:
          name: "{{ username }}"
          password: "{{ password }}"
          comment: Ansible test user
          state: present
...

